config/routes.rb
Roommate::Application.routes.draw do


  root 'properties#index'

  devise_for :users

  resources :properties
  

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :nav_state
  



  def nav_state

  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
  end

  def show
    @property = Property.find(params[:id])
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to properties_path, notice: "Succesfully added #{@property.name} to the list of available properties."
    else
      flash.now[:alert] = "Something went wrong, please try again"
      render :new
    end
  end

  def update

  end

  def destroy

  end

  def nav_state
    @nav = :properties
  end

  private

  def property_params
    params.require(:property).permit(:rent, :bedrooms, :bathrooms, :name, :address, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="masthead">
  <ul class="nav nav-pills pull-right">
    <li class="<%= 'active' if @nav == :properties %>"><%= link_to "Properties", properties_path %></li>
    <li><a href="#">About</a></li>
    <% if current_user %>
      <li><%= link_to 'Log out', destroy_user_session_path, class: 'btn', method: :delete %></li>
    <% else %>
      <li><%= link_to 'Log in', new_user_session_path, class: 'btn' %></li>
    <% end %>
  </ul>
  <h3 class="muted"><%= link_to "Roomater", :root %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roommate</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <%= render 'layouts/navbar' %>

    <%= render 'layouts/alerts' %>

    <span><%= "Signed in as: #{current_user.email}" if current_user %></span>


    <%= yield %>
  </div>

</body>
</html>

app/views/properties/index.html.erb
<h1>Properties</h1>
<%= link_to "new", new_property_path %>

<% if @properties %>

  <ul>
    <% @properties.each do |prop| %>
      <li><%=link_to prop.name, prop %>
        <ul>
          <li>Rent: <%= prop.rent %></li>
          <li>Address: <%= prop.address %></li>
          <li>Bedrooms/Bathrooms: <%= prop.bedrooms %>/<%= prop.bathrooms %></li>
        </ul>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/properties/new.html.erb
<h1>New Property</h1>


<%= form_for @property do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=f.label :name %>
    <%=f.text_field :name %>
  </div>
  <div class="field">
    <%=f.label :rent %>
    <%=f.text_field :rent %>
  </div>
  <div class="field">
    <%=f.label :bedrooms %>
    <%=f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%=f.label :bathrooms %>
    <%=f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%=f.label :address %>
    <%=f.text_field :address %>
  </div>

  <%= f.submit %>



<% end %>

<%= link_to 'back', :back %>

app/views/properties/show.html.erb
<h1><%= @property.name %></h1>

<ul>
  <li>rent: <%= @property.rent %></li>
  <li>bedrooms <%= @property.bedrooms %></li>
  <li>bathrooms: <%= @property.bathrooms %></li>
  <li>address: <%= @property.address %></li>

</ul>


<%= link_to 'back', :back %>